---
title: ""
format: html
toc: true
toc-title: Entry
---

```{r}
```

::: {.callout-note icon="false"}
This project is about addressing longstanding issues in American public policy and law, rather than reacting to current affairs. That said, some things should be said out loud. Those things will be said here.
:::

# August 25th, 2025

Today, the sitting president of the United States [claimed](https://www.axios.com/2025/08/25/trump-dictator-national-guard-dc) that "a lot of people are saying maybe we'd like a dictator". This was in response to criticism of his [escalating](https://www.theguardian.com/us-news/2025/aug/25/trump-washington-dc-national-guard-weapons) military occupation of Washington D.C. that has [parents writing notes](https://www.theguardian.com/us-news/2025/aug/25/washington-dc-daycare-workers-parents-immigration-raids) in an effort to prevent their children from being incarcerated alongside their undocumented caregivers. The president also signed several executive orders further [establishing a police state](https://www.axios.com/2025/08/25/trump-dc-executive-order-national-guard), [undermining constitutional rights to free speech](https://apnews.com/article/trump-executive-order-flag-burning-4628d588350db4f6baf10ae1d91f49c1), and depriving working class people of [due process](https://www.reuters.com/world/us/trump-signs-orders-aimed-ending-cashless-bail-policies-2025-08-25/). The harassment of Kilmar Abrego Garcia [continued](https://apnews.com/article/abrego-garcia-deportation-uganda-ice-2bad172b72c4871bc20bfa221b49b8bd), setting a dangerous precedent on just how far a vindictive administration can go to ruin a person's life. And in a blatant effort to manipulate election outcomes, the DOJ is being [weaponized](https://www.forbes.com/sites/antoniopequenoiv/2025/08/25/trump-says-doj-will-sue-california-pretty-soon-over-redistricting-proposal/) against the state of California's redistricting effort that is occurring as a response to the redistricting occurring in Texas at the behest of the administration.

The sitting president has regularly expressed admiration and jealousy of dictators . He has since moved to emulation. I am not sure the laws of this country were built to withstand a hostile takeover by the highest ranking government official emboldened by a complicit court and complacent congress.

# March 18th, 2025

The administration recently cited an [18th century law](https://uscode.house.gov/view.xhtml?path=/prelim@title50/chapter3&edition=prelim) last used during WWII to place US citizens in internment camps without trial, as justification to unlawfully deport hundred of Venezuelan immigrants to El Salvadorian prisons. The law, which has only been used three times previously, grants the president extensive detention and deportation over "all natives, citizens, denizens, or subjects of the hostile nation or government".

The administration's use of this law to deport *alleged* gang members is blatantly well outside of the law's actual scope which explicitly applies to wars with foreign nations or governments. Acknowledging such, a federal court ordered a delay to the administration's actions so they could go under legal review. The administration proceeded with the deportation regardless, calling the ruling itself unlawful.

The president does not and should not make the law. That is the whole point of our constitution.

In related new, the administration is trying to deport lawful residents for opposing a literal genocide that it supports.

Whether it be through the invocation of an old racist law or through ignoring the law altogether, it is clear this administration is seeking the authority to conjure up an enemy as a means of detaining and deporting as they please.

I say without hyperbole, you or I could be next.
